services:
  web:
    build: app/ 
    container_name: sqli-web
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: sqli_lab
      DB_USER: sqli_user
      DB_PASSWORD: sqli_pass

  db:
    image: mysql:8.0
    container_name: sqli-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli_lab
      MYSQL_USER: sqli_user
      MYSQL_PASSWORD: sqli_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

